CREATE DATABASE Edux;
USE Edux;

CREATE TABLE Perfil(
IdPerfil INT PRIMARY KEY IDENTITY NOT NULL,
Permissao VARCHAR(50) NOT NULL,
);

CREATE TABLE Instituicao(
IdInstituicao INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(255) NOT NULL,
UF CHAR(2) NOT NULL ,
Logradouro VARCHAR(255) NOT NULL,
Cidade VARCHAR(255) NOT NULL,
Complemento VARCHAR(255) NOT NULL,
Bairro VARCHAR(255) NOT NULL,
Numero VARCHAR(255) NOT NULL,
CEP VARCHAR(15) NOT NULL,
);

CREATE TABLE Categoria(
IdCategoria INT PRIMARY KEY IDENTITY NOT NULL,
Tipo VARCHAR(255) NOT NULL,
);

CREATE TABLE Curso(
IdCurso INT PRIMARY KEY IDENTITY NOT NULL,
Titulo VARCHAR(255) NOT NULL,
--
IdInstituicao INT FOREIGN KEY REFERENCES Instituicao(IdInstituicao) NOT NULL
);

CREATE TABLE Turma(
IdTurma INT PRIMARY KEY IDENTITY NOT NULL,
Descricao VARCHAR(255) NOT NULL,
--
IdCurso INT FOREIGN KEY REFERENCES Curso(IdCurso) NOT NULL
);

CREATE TABLE Usuario(
IdUsuario INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(255) NOT NULL,
Email VARCHAR(255) NOT NULL,
Senha VARCHAR(255) NOT NULL,
DataCadastro DATETIME,
DataUltimoAcesso DATETIME,

--
IdPerfil INT FOREIGN KEY REFERENCES Perfil(IdPerfil) NOT NULL
);

CREATE TABLE ProfessorTurma(
IdProfessorTurma INT PRIMARY KEY IDENTITY NOT NULL,
Descricao VARCHAR(255) NOT NULL,

--
IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL,
IdTurma INT FOREIGN KEY REFERENCES Turma(IdTurma) NOT NULL,
);

CREATE TABLE Dica(
IdDica INT PRIMARY KEY IDENTITY NOT NULL,
Texto VARCHAR(255) NOT NULL,
Imagem VARCHAR(150) NOT NULL,
--
IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL,
);

CREATE TABLE Curtida(
IdCurtida INT PRIMARY KEY IDENTITY NOT NULL,
--
IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL,
IdDica INT FOREIGN KEY REFERENCES Dica(IdDica) NOT NULL,
);

CREATE TABLE AlunoTurma(
IdAlunoTurma INT PRIMARY KEY IDENTITY NOT NULL,
Matricula VARCHAR(50) NOT NULL,
--
IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL,
IdTurma INT FOREIGN KEY REFERENCES Turma(IdTurma) NOT NULL,
);

CREATE TABLE Objetivo(
IdObjetivo INT PRIMARY KEY IDENTITY NOT NULL,
Descricao VARCHAR(255) NOT NULL,
--
IdCategoria INT FOREIGN KEY REFERENCES Categoria(IdCategoria) NOT NULL,
);

CREATE TABLE AlunoObjetivo(
IdAlunoObjetivo INT PRIMARY KEY IDENTITY NOT NULL,
Nota DECIMAL DEFAULT NULL,
DataAlcancada DATETIME,
--
IdAlunoTurma INT FOREIGN KEY REFERENCES AlunoTurma(IdAlunoTurma) NOT NULL,
IdObjetivo INT FOREIGN KEY REFERENCES Objetivo(IdObjetivo) NOT NULL,
);